// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using TradingApi.ModelObjects.Bitfinex.Json.OrderbookTypes;

namespace TradingApi.ModelObjects.Bitfinex.Json
{

   public class BitfinexOrderBookGet
   {

      [JsonProperty("bids")]
      public Bid[] Bids { get; set; }

      [JsonProperty("asks")]
      public Ask[] Asks { get; set; }
   }

}
