// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace TradingApi.ModelObjects.Bitfinex.Json
{

   public class BitfinexTradesGet
   {

      [JsonProperty("timestamp")]
      public int Timestamp { get; set; }

      [JsonProperty("tid")]
      public int Tid { get; set; }

      [JsonProperty("price")]
      public string Price { get; set; }

      [JsonProperty("amount")]
      public string Amount { get; set; }

      [JsonProperty("exchange")]
      public string Exchange { get; set; }

      [JsonProperty("type")]
      public string Type { get; set; }

      public override string ToString()
      {
         var str = string.Format("Timestamp: {0} - tid: {1}, Price: {2}, Amount: {3}, Exchange: {4}, Type: {5}",
                                  Timestamp, Tid, Price, Amount, Exchange, Type);
         return base.ToString();
      }
   }

}
